- lib/hatchet/app.rb
- test/hatchet/app_test.rb
Now that there's more than one cedar stack on Heroku. It'd be nice to be able to specify the stack on app create vs after the app is created. This will reduce the calls by one and not force us to do an empty git push and switch.
> allow the app to set the stack on create

- hatchet.gemspec
This fixed some [failures on the Scala buildpack](https://travis-ci.org/heroku/heroku-buildpack-scala/jobs/243066806) that I believe may be related to the [V2 Brownouts](https://status.heroku.com/incidents/1188).
Note that CI is failing due to the CLI v6 update. But even running the tests locally, I get failures that appear to be related to heroku-16 and ruby 1.9.3.
> Upgrade platform-api to version 2

- lib/hatchet/reaper.rb
When running multiple test workers against the same account it’s possible that two of them try to delete the same app, when this happens we should not be raising an error, but instead see if the user is under the “threshold”, if they are do nothing, if not the next app should be removed. Repeat until the user is under the threshold.
> Fix double deletes

- CHANGELOG.md
- lib/hatchet.rb
- lib/hatchet/api_rate_limit.rb
- lib/hatchet/app.rb
- lib/hatchet/reaper.rb
- lib/hatchet/version.rb
When deploying lots of apps for a buildpack it’s very easy to hit the Heroku API rate limit. When this happens builds start to fail with 422 status. It’s pretty cryptic. Usually what happened is there are multiple CI services running at once and they flooded the API.
This patch adds a tiny sleep before each API call. The sleep is proportional to the amount of capacity left in your rate limit bucket. If you have lots of requests left then the sleep is barely noticeable. If you have only 1 left, then you’ll be sleeping for a full 60 seconds.
> Add API rate limits

- CHANGELOG.md
- lib/hatchet/api_rate_limit.rb
- lib/hatchet/app.rb
- lib/hatchet/test_run.rb
- lib/hatchet/version.rb
This is not ideal since the call to `@platform_api.rate_limit.info["remaining”]` takes away from our rate limit, however it doesn’t look like all the API endpoints for CI are currently emitting a `"Ratelimit-Remaining”` header.
> Re-use ApiRateLimit in CI API calls

- lib/hatchet/app.rb
- test/hatchet/app_test.rb
It’s common that someone might want have a “blank” template that then gets modified for each test.
For example you could use this to add a file to the app:
```ruby
app = Hatchet::Runner.new("default_ruby”, before_deploy: -> { `echo "gem ‘rake’" >> Gemfile && bundle install` }
```
If this block changes the git directory the contents will automatically be saved as a new git commit.
> Provide safe ability to modify files on disk

- lib/hatchet/app.rb
- test/hatchet/heroku_api_test.rb
Previously you had to 
```ruby
app = Hatchet::Runner.new(“default”)
app.set_config({
“FOO” => "http://localhost:3000",
“BAR” => "10000"
})
```
Now you can:
```ruby
app = Hatchet::Runner.new(“default”, config: {
“FOO” => "http://localhost:3000",
“BAR” => "10000"
})
```
> Allow config to be set at initialization

- lib/hatchet/app.rb
- test/different-folder-for-checked-in-repos/default_ruby/Gemfile
- test/different-folder-for-checked-in-repos/default_ruby/Gemfile.lock
- test/hatchet/local_repo_test.rb
Minimum viable changes to have directories locally instead of as separate git repos
This probably breaks a bunch of things... 🙈
> Support local directories for fixtures

- .travis.yml
- bin/hatchet
- etc/ci_setup.rb
- etc/setup_heroku.sh
- lib/hatchet/tasks.rb
When the setup script is provided as a rake task it assumes rake is installed and there is a Rakefile present. Since we already have a CLI we can instead expose that script as a CLI command instead.
> Move setup script into it's own command.

- etc/ci_setup.rb
'git config --get user.name' returns 'Travis CI', which because unquoted gets interpreted as two operators by if, and breaks:
```
$ bundle exec hatchet ci:setup
sh: 1: [: Travis: unexpected operator
```
```
sh-3.2$ if [ `git config --get user.name` ]; then echo 'already set'; else echo 'not set'; fi
sh: [: David: unary operator expected
```
much easier is to just use the exit status of --get instead
> fix /bin/sh if incompat

- lib/hatchet/app.rb
- test/hatchet/app_test.rb
- Allows options without values (say `--no-notify`) by passing `nil` as the value
- Correctly order and separate our options from the actual command using `--`
- Always report back the invoked programs's exit status, so it can be checked using `$?.exitstatus`
I wonder if we should *not* `.to_s.shellescape` the `command` part now. It leads to the whole thing being one quoted string, which the CLI then unpacks again: https://github.com/heroku/cli/blob/master/packages/run-v5/lib/helpers.js#L6-L10
All that potentially leads to is quoting madness in special cases; changing it as well *should* not impact any existing calls
> app.run fixes

- CHANGELOG.md
- lib/hatchet/app.rb
- lib/hatchet/version.rb
- test/hatchet/app_test.rb
this is to e.g. allow preventing the use of --exit-code, which does not work with procfile entry names
> 4.0.9: make default options overridable in App#run

- .travis.yml
- hatchet.gemspec
- test/hatchet/ci_test.rb
- test/hatchet/ci_three_test.rb
- test/hatchet/ci_too_test.rb
- test/test_helper.rb
- tmp/parallel_runtime_test.log
CI test is the slowest test, therefore the whole suite is dependent on the amount of time it takes to run.
Previously we were doing 3 CI test deployments in one file, we can make the suite much faster by instead splitting them into 3 different files.
I think we could further speed things up by maybe turning off the retry behavior of the CI test that we know will fail?
> Make tests faster by splitting out CI tests into multiple files

- lib/hatchet/app.rb
- test/hatchet/local_repo_test.rb
Sometimes in a test you don't know of a bit of code will modify global state such as environment variables. To be extra safe we can run these actions inside of a fork.
Here's an example of some tests that were accidentally mutating the current env https://github.com/heroku/heroku-buildpack-ruby/pull/918.
> Safer tests by not mutating current process

- lib/hatchet/app.rb
- lib/hatchet/test_run.rb
- test/hatchet/ci_too_test.rb
- write the stack into `app.json` if set, otherwise tests always run on heroku-18
- copy app config into the `test` `env` in `app.json`, so config set on the app makes it into the test run
- couple the app to the CI pipeline, otherwise the pipeline has no apps after the CI run finishes (test run app gets deleted after run), and that'll purge the pipeline, leading to 403s on CI run progress poll or in pipeline deletion
> Heroku CI fixes

- CHANGELOG.md
- lib/hatchet.rb
If `HATCHET_BUILDPACK_BRANCH` nor `HEROKU_TEST_RUN_BRANCH` are set, Hatchet falls back to `Hatchet.git_branch` which tries to resolve the branch using git. Before using actual git, it will look for the `TRAVIS_BRANCH` environment variable and use its value if available instead.
`TRAVIS_BRANCH` works fine unless the build is a pull-request. In that case, it will contain the target branch not the actual pull-request branch. This results in Hatchet tests running silently against the target branch (most of the time `master`) and not testing the actual changes in the PR. `TRAVIS_PULL_REQUEST_BRANCH` contains the correct branch but will be empty for push builds. 
See: https://docs.travis-ci.com/user/environment-variables/
> Use TRAVIS_PULL_REQUEST_BRANCH over TRAVIS_BRANCH if available

- CHANGELOG.md
- README.md
- lib/hatchet/app.rb
- test/hatchet/app_test.rb
It's really hard to remember `Hatchet::App.default_buildpack` and it's a lot to type. This PR adds the ability to pass in a symbol `:default` that will be expanded to `Hatchet::App.default_buildpack` in the buildpacks array.
> Add alias for Hatchet::App.default_buildpack

- CHANGELOG.md
- README.md
- hatchet.lock
- lib/hatchet/app.rb
- lib/hatchet/test_run.rb
- test/hatchet/ci_four_test.rb
- test/test_helper.rb
I needed to run a test twice to assert that the cache was used for the Ruby buildpack. I hacked it:
https://github.com/heroku/heroku-buildpack-ruby/blob/facd23708feff15d5bdbfd0455dc470a21b11a76/spec/hatchet/ci_spec.rb#L41-L43
This PR gives a supported API instead to call `TestRun#run_again`.
While working on this, I discovered that the test run wasn't being run inside the temp directory. So I fixed that bug, I also added support for `before_deploy`.
> Allow for Test re-runs

- CHANGELOG.md
- README.md
- lib/hatchet/app.rb
- lib/hatchet/version.rb
- test/hatchet/app_test.rb
Right now if someone wrote this code:
```
app.run("ls && rm -rf /")
```
It would be interpreted as:
```
$ heroku run ls
$ rm -rf /
```
Which is surprising at best and harmful at worst. This PR auto escapes commands by default. This was the default behavior before https://github.com/heroku/hatchet/pull/58/commits/59f76d487470cd7815b4bd3c35225d8aa1b93d4c which removed shellescape-ing, but this edge case was not considered.
If the user wants more flexibility, they can specify they're using their own escaping by passing in `raw: true`.
I also updated the method signature for `App#run` so that the `heroku:` option can be used without having to specify a `nil` argument in the middle, I'm deprecating the ReplRunner interface (which was pretty broken and I don't believe used) so that we can …
> [Close #71] Do not escape to local system shell

- CHANGELOG.md
- README.md
- bin/hatchet
- hatchet.json
- hatchet.lock
- lib/hatchet/version.rb
- test/hatchet/lock_test.rb
Currently `hatchet lock` locks all repos to a specific commit, but there are times where a maintainer wants the latest commit instead of a specific version. For example if the ruby buildpack maintainer wanted to make sure that the `ruby-getting-started` app.
> Allow using `master` as a lock target

- CHANGELOG.md
- README.md
- lib/hatchet/reaper.rb
- spec/unit/reaper_spec.rb
There are cases where Hatchet deletes an app as it is being used/deployed. For example if you've configured a test runner to concurrently execute 25 tests, but you've set HATCHET_APP_LIMIT=20` then one test process will create an app as another is trying to destroy it. This results in odd errors like this in the deploy:
```
remote: !	No such app as hatchet-t-522c335bea.
```
To prevent this we can set a configurable minimum time to live for applications. In the above scenario where we want to run 25 apps, but have set a maximum of 20 then Hatchet would wait until the oldest app was 7 minutes old before deleting it. This should give the test a chance to finish before continuing and deleting the application.
This value can be configured by the environment variable:
``` …
```
> [close #89] Set minimum Time to Live for apps

- CHANGELOG.md
- hatchet.gemspec
- lib/hatchet/app.rb
- lib/hatchet/git_app.rb
- lib/hatchet/version.rb
- spec/hatchet/allow_failure_git_spec.rb
When a release fails to execute the app is never deployed, for example if you were to run:
```ruby
git push heroku master && heroku run ls
```
Both commands will run, but `heroku run ls` will be empty since the release never finished. This creates weird to debug hatchet tests as the deploy will work but any subsequent `app.run(<cmd>)` will fail in strange ways. You can see an example of a failure in #92.
This PR seeks to make this behavior more explicit, by explicitly failing on an incomplete release. This is a breaking change so it's a major version bump.
> [close #92] Fail on release failure

- CHANGELOG.md
- lib/hatchet/api_rate_limit.rb
- lib/hatchet/app.rb
- lib/hatchet/git_app.rb
- spec/hatchet/app_spec.rb
When an app is attempted to be deployed it can fail due to an API rate limit like this:
```
Hatchet::App::FailedDeployError:
Could not deploy 'hatchet-t-3ae0c484c6' (rails5_ruby_schema_format) using 'Hatchet::GitApp' at path: 'repo_fixtures/repos/ci/rails5_ruby_schema_format'
if this was expected add `allow_failure: true` to your deploy hash.
output:
Buildpack: nil
Repo: https://git.heroku.com/hatchet-t-3ae0c484c6.git
remote: Compressing source files... done.        
remote: Building source:        
remote: 
remote: !    Your account reached the API rate limit Please wait a few minutes before making new requests        
remote: 
To https://git.heroku.com/hatchet-t-3ae0c484c6.git
! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to …
```
> Rate throttle `git push heroku master`

- CHANGELOG.md
- README.md
- lib/hatchet/app.rb
- lib/hatchet/reaper.rb
- lib/hatchet/reaper/app_age.rb
- lib/hatchet/reaper/reaper_throttle.rb
- spec/hatchet/app_spec.rb
- spec/hatchet/ci_spec.rb
- spec/unit/reaper_spec.rb
Issue: https://github.com/heroku/hatchet/issues/90
When the reaper was originally introduced there was a limit of 100 apps per Heroku account. As of today my account has 224 apps, because it is connected to multiple organizations. This means when I run with my local account, every time `reaper.cycle` is called it deletes a hatchet app even though it doesn't need to.
The "fix" for this is to remove the HEROKU_APP_LIMIT setting and instead trying to detect when we've been going over the limit.
This was accomplished by forcing the reaper to reap once when an exception is raised in the creation of an app. (Note reaping does not guarantee deletion of an app if none are "finished" or old enough). It can also trigger the issue with "minimum time to live" listed below if a parallel run was …
> App Reaper Redesign

- CHANGELOG.md
- lib/hatchet/app.rb
- lib/hatchet/git_app.rb
- lib/hatchet/shell_throttle.rb
- spec/unit/shell_throttle.rb
Building off of https://github.com/heroku/hatchet/pull/98 we now also throttle calls to `heroku run`.
> Throttle `heroku run` calls

- .circleci/config.yml
- CHANGELOG.md
- README.md
- lib/hatchet/app.rb
- lib/hatchet/reaper.rb
- spec/hatchet/app_spec.rb
By default free apps can only run one "one-off" dyno at a time. For example if you run `heroku run rails c` you cannot run `heroku run ls` until the first command finishes (on a free app). There's a quirk about the distributed nature of the heroku platform in that once `heroku run <command>` returns, it does not guarantee that the dyno has completely been shutdown, but only that shutdown has started. This means that if you're wanting to do multiple `app.run` calls in a test, you need to add sleeps to be safe:
```ruby
Hatchet::Runner.new("default_ruby").deploy do |app|
expect(app.run("ls -a Gemfile 'foo bar #baz'")).to match(/ls: cannot access 'foo bar #baz': No such file or directory\s+Gemfile/)
sleep 4
expect((0 != $?.exitstatus)).to be_truthy
app.run("ls erpderp", heroku: ({ "exit-code" …
```
> Allow multiple concurrent one-off dynos to run

- CHANGELOG.md
- lib/hatchet/reaper.rb
- When an app is deleted too quickly then it might come back as a 403. 
- When that happens log the request ID for future debugging if needed.
> Ignore 403 on App delete, Log request ID

- CHANGELOG.md
- README.md
Found by VSCode's spell check plugin whilst working on #105.
> Fix typos in README.md and CHANGELOG.md

- CHANGELOG.md
- hatchet.gemspec
- lib/hatchet/app.rb
Since it's been deprecated as of Hatchet 5.0.0, and removing support means we can drop the dependency on `repl_runner`, and so one of the consumers of `activesupport`.
The addition of `activesupport` to Hatchet's gemspec is required since Hatchet itself relies upon `activesupport` but was previously relying on it being pulled in implicitly via `repl_runner`. Later PRs will remove the dependency on `activesupport` entirely.
This is a breaking change, so will require a bump to Hatchet 7.0.0. However the next part of #103 will also be a breaking change (dropping support for `blank?` / removing the dependency on `activesupport`), so please don't release 7.0.0 until the next PR also lands. We also may want to release the current changes on `main` as a 6.x release, in which case I'll rebase …
> Remove support for passing a block to App#run

- spec/hatchet/allow_failure_git_spec.rb
Since `teardown!` is not called unless `deploy` is called with a block, it was never being called for these test cases.
> [changelog skip] Fix teardown not called in tests

- CHANGELOG.md
- bin/hatchet
- spec/hatchet/lock_spec.rb
- Allow `hatchet lock` to be called on a new app
- Allow `hatchet.lock` to specify a different branch than what github currently has as the default
> Fixes to `hatchet lock`

- CHANGELOG.md
- README.md
- lib/hatchet/app.rb
- lib/hatchet/git_app.rb
- spec/hatchet/allow_failure_git_spec.rb
When a deploy succeeds but the release fails the git remote retains the contents of the `git push`. This means if you immediately try to push again that you'll get a `Everything up-to-date` from the remote and Heroku will not try to re-build your project.
We don't want that behavior, we want to retry on a failed release incase it's intermittent. This PR adds an empty commit when a failed release is detected.
> [close #109] Allow retrying failed release

- CHANGELOG.md
- lib/hatchet/reaper.rb
- spec/unit/reaper_spec.rb
```
$ bundle exec hatchet destroy --all
home/travis/.rvm/gems/ruby-2.5.3/gems/heroku_hatchet-7.1.0/lib/hatchet/reaper.rb:83:in `destroy_all': undefined local variable or method `get_apps' for #<Hatchet::Reaper:0x000000000317f400> (NameError)
from /home/travis/.rvm/gems/ruby-2.5.3/gems/heroku_hatchet-7.1.0/bin/hatchet:112:in `destroy'
from /home/travis/.rvm/gems/ruby-2.5.3/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
from /home/travis/.rvm/gems/ruby-2.5.3/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
from /home/travis/.rvm/gems/ruby-2.5.3/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
from /home/travis/.rvm/gems/ruby-2.5.3/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
from /home/travis/.rvm/gems/ruby-2.5.3/gems/heroku_hatchet-7.1.0/bin/hatchet:186:in `<top …
```
> Fix destroy all functionality

- CHANGELOG.md
- lib/hatchet/git_app.rb
- spec/hatchet/git_spec.rb
When I shipped support for the main branch I only checked that the lock file correctly installed the main branch, but never checked it could be deployed. 
In our deploy we previously ran `git push heroku master` which is short for `git push master:master` and this fails since there's no master branch of that repo. This force deploys HEAD instead.
> Fix support for deploying `main` branch

- CHANGELOG.md
- lib/hatchet.rb
- spec/hatchet/git_spec.rb
We've been accidentally running all hatchet tests on CircleCI against `main`/`master` instead of the correct buildpack branch by accident.
https://twitter.com/schneems/status/1303785823263883264
> Fix branch detection on CircleCI 

- CHANGELOG.md
- README.md
- bin/hatchet
- lib/hatchet.rb
- lib/hatchet/init_project.rb
- lib/hatchet/templates/Gemfile.erb
- lib/hatchet/templates/buildpack_spec.erb
- lib/hatchet/templates/check_changelog.erb
- lib/hatchet/templates/circleci_template.erb
- lib/hatchet/templates/dependabot.erb
- lib/hatchet/templates/hatchet_json.erb
- lib/hatchet/templates/spec_helper.erb
- spec/unit/init_spec.rb
To make adding Hatchet tests to an existing project easier and faster I've created a `$ hatchet init` command. 
This will generate:
- Gemfile
- hatchet.json
- spec/spec_helper.rb
- spec/hatchet/buildpack_spec.rb
- .circleci/config.yml
- .github/dependabot.yml
- .gitignore
Then run `bundle install` and `hatchet install`. Once this is done then you can start writing tests using Hatchet.
> Bootstrap a buildpack with `hatchet init`

- CHANGELOG.md
- lib/hatchet/app.rb
- spec/hatchet/app_spec.rb
- spec/hatchet/local_repo_spec.rb
As described in https://github.com/heroku/heroku-buildpack-ruby/pull/1061 it's possible to accidentally modify disk when you didn't intend to using the `setup!` API. This PR fixes that by moving all the disk mutating calls to it's own method and ensuring it only gets called while in the directory.
> Move disk modifying operations out of `setup!`

- CHANGELOG.md
- lib/hatchet/app.rb
- spec/spec_helper.rb
Currently if you want to set HATCHET_BUILDPACK_BASE, you need to do so before you `require 'hatchet'` which is unexpected. By evaluating this env var every time a new app is created it allows the developer to set this env var when they want instead of before requiring the library.
The other change here is to no longer default to a buildpack. While it was useful for defaulting to the Ruby buildpack when only the ruby buildpack used this library, it is confusing when setting up a new buildpack to have deploys seemingly happen but it to not use your buildpack code. This can be fixed by raising a helpful error when HATCHET_BUILDPACK_BASE is not set. However that's a breaking change. For now I'm just deprecating that fallback behavior.
> [close #83] HATCHET_BUILDPACK_BASE updates

- CHANGELOG.md
- lib/hatchet/app.rb
- spec/hatchet/app_spec.rb
```
14) Java a simple java app on jdk-openjdk-9.0.4 should deploy
Failure/Error:
Hatchet::Runner.new(
buildpacks: ["https://github.com/heroku/heroku-buildpack-java"],
config: {
"JVM_COMMON_BUILDPACK" => "https://api.github.com/repos/heroku/heroku-buildpack-jvm-common/tarball/#{jvm_common_branch}"
}
).tap do |app|
ArgumentError:
unknown keywords: :buildpacks, :config
```
This PR defaults to a value then raises an error when that value is not assigned manually by the programmer.
> [close #88] Raise error when no source given

- CHANGELOG.md
- lib/hatchet/app.rb
- spec/hatchet/app_spec.rb
For intermittent failures it's important to get as much debugging information as possible about the test in progress. This PR annotates any rspec expectation failures that happen in a `deploy {}` block with the application name. Here's an example of what it will look like:
```
Failure/Error: expect(true).to eq(false)
App: hatchet-t-873bcea87c (default_ruby)
expected: false
got: true
(compared using ==)
Diff:
@@ -1 +1 @@
-false
+true
``` 
In this example if the failure was due to an `app.run` then we could manually `app.run` against the same app (assuming it had not been reaped yet) in order to better debug.
> [close #50] Annotate rspec errors

- CHANGELOG.md
- lib/hatchet.rb
- lib/hatchet/app.rb
- lib/hatchet/git_app.rb
- lib/hatchet/heroku_run.rb
- spec/unit/heroku_run_spec.rb
App#run (`heroku run`) commands sometimes return empty strings. We would love to know WHY so this pr does two things:
- Adds debugging information when this happens
- Retries the commands by default up to 3 times
I figure that it's unlikely someone will be running a `heroku run` session and expecting an empty result, unless that's how they detect some failure mode. If they are expecting it, then they can manually specify `retry_on_empty: false`.
For now the only extra debug info we're providing is the contents of releases. In the future we could enable `DEBUG="*"` by default and separately capture stdout versus stderr and output the full debug contents of stderr if needed.
In reality, the retry behavior here will likely be "good enough" to make this issue functionally disappear.
I …
> [close #131] Retry App#run on empty results

- CHANGELOG.md
- README.md
- lib/hatchet/app.rb
- lib/hatchet/test_run.rb
It's confusing that App#directory points to the original source code instead of the temp dir where the source is currently. Let's make this more explicit by deprecating that method.
> Deprecate App#directory

- CHANGELOG.md
- lib/hatchet/test_run.rb
Otherwise, tar will often say 'file changed as we read it' because it's packing up the contents of the directory, and the directory suddenly contains the tarball itself as a new file
> create CI slug tarball outside cwd

- CHANGELOG.md
- lib/hatchet/app.rb
- spec/hatchet/local_repo_spec.rb
When an error is raised inside of `in_directory_fork` it writes over the existing contents so if there's any debug output that was added it gets written over. 
This fixes that behavior by making stdout and stderr append to the log file instead of
> Fix debug output for `in_directory_fork`

- CHANGELOG.md
- lib/hatchet/app.rb
From this:
```
$ be rspec spec/unit
.... ›   Warning: token will expire 10/15/2021
›   Use heroku authorizations:create to generate a long-term token
..............
Finished in 20.48 seconds (files took 0.42776 seconds to load)
18 examples, 0 failures
```
To this:
```
$ be rspec spec/unit
..................
Finished in 20.48 seconds (files took 0.42776 seconds to load)
18 examples, 0 failures
```
> [close #147] Quiet API token

- spec/hatchet/ci_spec.rb
The `rails5_ci_fails_no_database` test fixture now fails after the Heroku default stack changed from `heroku-18` to `heroku-20`, since the fixture's `Gemfile.lock` specifies Ruby 2.4.1, when the oldest Ruby on Heroku-20 is Ruby 2.5.8.
As a stop-gap until the external-repo fixture is updated to use newer Ruby, the tests now explicitly use the Heroku-18 stack rather than whatever happens to be the platform default.
Fixes #173.
> Make `rails5_ci_fails_no_database` tests use Heroku-18 [changelog skip]

- CHANGELOG.md
- etc/setup_heroku.sh
Since the APT installer takes 3.5x longer than the non-APT version, and offers little benefit in a CI environment.
Closes #169.
> Use the standalone installer for 'ci:install_heroku' rather than APT

- CHANGELOG.md
- etc/ci_setup.rb
In Git 2.30+, the `git init` command outputs a warning if `init.defaultBranch` is not set in the Git configuration:
https://github.com/git/git/commit/675704c74dd4476f455bfa91e72eb9e163317c10
Setting this default in `ci:setup` ensures that the warning does not spam CI logs every time `git init` is run.
This config change only affects new repos created by `git init`, not repositories cloned using `git clone`. Hatchet uses `git init` when the path passed to `App.new` is a local directory, and not a repository cloned via `hatchet.lock`.
This changes the default branch for new repos from `master` to `main`, however this works without further changes, since Hatchet already uses `git push HEAD:main`, where `HEAD` will reference the current branch regardless of its choice of name.
This change is …
> Set 'init.defaultBranch' in ci:setup to suppress 'git init' warning

- CHANGELOG.md
- lib/hatchet/reaper.rb
> Fix typo in the reaper "Duplicate destroy attempted" message

- CHANGELOG.md
- README.md
- lib/hatchet/app.rb
- spec/hatchet/app_spec.rb
This saves having to specify a `stack` every time `App` is created, when using CI runs with a specific global default stack.
Closes #163.
> Add `HATCHET_DEFAULT_STACK` for configuring the default stack

- CHANGELOG.md
- lib/hatchet/git_app.rb
- spec/unit/shell_throttle_spec.rb
There were another two variations of a rate limit error message that previously weren't being detected as an error related to exceeding the rate limit. This meant Hatchet wouldn't perform request backoff, which would result in cascading failures.
Fixes #176.
> Handle additional variations of rate limit error messages

- CHANGELOG.md
- lib/hatchet/config.rb
- spec/hatchet/config_spec.rb
Previously if a custom Hatchet `directory` was defined in `hatchet.json`, passing a fixture name of the full repository name would not work.
Fixes #161.
> Fix repository path lookup when custom Hatchet directory set

- CHANGELOG.md
- lib/hatchet/app.rb
- spec/hatchet/app_spec.rb
To improve performance and so that it still returns the correct result if called again inside an `app.deploy` block.
Fixes #180.
> Memoize Hatchet::App.default_buildpack

- CHANGELOG.md
- lib/hatchet/heroku_run.rb
- spec/hatchet/app_spec.rb
- spec/unit/heroku_run_spec.rb
The rate limiting messages are delivered via the `heroku` cli to stderr which we're currently not capturing. This means that when we check stdout there will never be a rate limit message, so our rate limiting and retry code never fires. This is documented in #156.
This PR fixes this by moving from exec-ing the process via backpacks to using `Open3.capture3` which captures stderr in addition to stdout. The biggest caveat is that it does not set the value for $? Which some tests are likely relying on. To prevent this change from breaking backwards compat we will exec an `exit` with the same status code. It's not ideal, but it will work.
In the future we may want to consider deprecating returning a string and moving to return an object that holds a status value instead.
> [close #156] Capture stderr from `heroku run`

- lib/hatchet/app.rb
Scaling to size 'free' is no longer possible, so this is now causing test failures for users of run_multi
GUS-W-12421816
> Scale to size 'basic' in App.teardown!

- CHANGELOG.md
- lib/hatchet.rb
- lib/hatchet/app.rb
Since Circle CI, GitHub Actions, and Heroku CI are widely used internally and across the ecosystem, I thought it might make sense to centralize this detection. Otherwise, we're looking at copying it around as discussed in https://github.com/heroku/heroku-buildpack-nodejs/pull/1033#pullrequestreview-1120488083 and https://github.com/heroku/hatchet/issues/179.
> Add branch detection for more CI providers

- CHANGELOG.md
- README.md
- bin/hatchet
- lib/hatchet/app.rb
- lib/hatchet/reaper.rb
- spec/hatchet/app_spec.rb
- spec/hatchet/ci_spec.rb
- spec/unit/reaper_spec.rb
- Breaking change: Delete apps on teardown. Previously hatchet would delete apps lazilly to help with debugging. This allowed developers to inspect logs and `heroku run bash` in the event of an unexpected failure. In practice it's rarely needed and means accounts retain a lot of Heroku apps. Previously there was no cost to retaining applications, but now `basic` applications incur a charge. Change details:
- The application teardown process now deletes applications directly.
- To skip destroying applications on teardown set `HEROKU_DEBUG_EXPENSIVE=1`. This will keep your applications around so that you can introspect why one failed.
- When Hatchet needs a new application it will first delete all applications that are created at least `HATCHET_ALIVE_TTL_MINUTES` ago. If it cannot delete …
> Change App#teardown! to delete apps immediately

- CHANGELOG.md
- lib/hatchet.rb
- lib/hatchet/version.rb
- spec/unit/default_ci_branch_spec.rb
The call to `empty?` will fail if the key GITHUB_HEAD_REF does not exist.
Before fixing this problem, I extracted the logic to its own testable class. Then I added tests, which also showed that `GITHUB_REF_NAME` would never be returned either (a previously unknown bug) because `!@env["GITHUB_HEAD_REF"]&.empty?` will always be truthy unless the key exists and it's empty.
This would (possibly) be cleaner with pattern matching. Ruby has pattern matching but we can't use it yet due to minimum supported Ruby version https://docs.ruby-lang.org/en/3.0/syntax/pattern_matching_rdoc.html.
Close #196
> Fix bug #196 && prepare v8.0.0 release

- CHANGELOG.md
- bin/hatchet
- lib/hatchet/app.rb
- lib/hatchet/reaper.rb
- lib/hatchet/version.rb
- spec/hatchet/app_spec.rb
- spec/unit/reaper_spec.rb
When multiple processes are attempting to cull the old apps list to free up enough space (to get under the limit), each will try to delete the same app.
We already introduced a file based lock for multiple processes on the same machine. However the lock was not being used while clearing out old apps. That has been added.
This file locking doesn't fix the problem, but it limits it instead of N machines running M processes, you only have to account for N machines. 
The next fix is that when a duplicate deletion is detected, instead of having all machines continue on as fast as possible, the machines that "lost" the race will sleep to allow the winner to continue removing apps. When it wakes up it will refresh its API list and try again. This will happen in a loop until there are no more …
> Fix multiple duplicate deletion attempts

- CHANGELOG.md
- lib/hatchet/app.rb
- lib/hatchet/version.rb
- spec/hatchet/app_spec.rb
- spec/unit/app_spec.rb
The deploy method can be called within the a deploy block. When this happens, `teardown!` triggers an immediate app deletion which will cause other code within that block to be deleted.
If I could re-write all of this, I would use a different abstraction instead of having App be the god-object. Since I'm living with this existing domain model, we can record the outermost block ID and only fire teardown when that block is exiting. This method ensures that teardown is only ever called once.
> Only call teardown once per outer block

- spec/hatchet/app_spec.rb
- spec/hatchet/ci_spec.rb
The "create app with stack" has been pending for a long time. The "create app with HATCHET_DEFAULT_STACK is tightly coupled to the stack and providing limited value.
close #206
> Remove tests

- .github/workflows/ci.yml
- CHANGELOG.md
Since Ruby 3.3 is the default Ruby version when using the `ruby` / `ruby@3` Homebrew package aliases, so has a high chance of being what people are now using locally.
https://www.ruby-lang.org/en/news/2023/12/25/ruby-3-3-0-released/
> Test against Ruby 3.3 in CI

- CHANGELOG.md
- lib/hatchet/reaper.rb
Hatchet creates apps when you need them (up to a limit) and then when that limit is hit, it will attempt to delete old apps.
One of the bottlenecks that Hatchet faces is API limits. Hatchet relies on rate throttling https://www.schneems.com/2020/07/08/a-fast-car-needs-good-brakes-how-we-added-client-rate-throttling-to-the-platform-api-gem/ to slow down and spread out API requests, but there's a point where too many requests and processes sleeping for too long can result in failures.
Hatchet is also distributed as multiple test runs on multiple machines. So we have to assume that if our process is trying to delete apps, that other processes might as well and that creates race conditions. If two (or more) servers try to delete the same resource then one will get a 404 response.
The reaper …
> Remove regex from 404 duplicate deletion check

- spec/hatchet/ci_spec.rb
Tests are failing with this output:
```
expected "-----> Building on the Heroku-24 stack\n-----> Fetching https://github.com/heroku/heroku-buildpack-r...: rake test\n505b817aba132559e51bfc599fe8a1c7\n-----> Ruby buildpack tests completed successfully\n" to match "Using rake"
Diff:
@@ -1 +1,89 @@
-Using rake
+-----> Building on the Heroku-24 stack
+-----> Fetching https://github.com/heroku/heroku-buildpack-ruby.git#main buildpack...
+       buildpack downloaded
+-----> Ruby app detected
+-----> Installing bundler 2.3.25
+-----> Removing BUNDLED WITH version in the Gemfile.lock
+-----> Setting up Test for Ruby/Rack
...
+-----> Installing dependencies using bundler 2.3.25
+       Running: BUNDLE_WITHOUT='development' BUNDLE_PATH=vendor/bundle BUNDLE_BIN=vendor/bundle/bin BUNDLE_DEPLOYMENT=1 …
```
> Fix failing tests

- CHANGELOG.md
- README.md
- lib/hatchet/tasks.rb
- lib/hatchet/version.rb
- spec/hatchet/app_spec.rb
> Fix hatchet:setup_ci not printing
